# Generated by Django 3.2.16 on 2025-11-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0003_subscriptionplan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersubscription",
            name="subscribe_type",
            field=models.CharField(max_length=128),
        ),
    ]
