# Generated by Django 3.2.16 on 2025-11-11 07:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0004_alter_usersubscription_subscribe_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="title",
        ),
    ]
