# Generated by Django 3.2.16 on 2025-11-11 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0005_remove_subscriptionplan_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="tariff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plans",
                to="subscriptions.tariff",
            ),
        ),
        migrations.AlterField(
            model_name="tariff",
            name="tariff_type",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
